### ISSUE TITLE
don't claim syntax error at ; when ; was implied in the first place

### ISSUE THREAD

**Issue by riastradh-probcomp** [probcomp/bayeslite#90]
Hopefully ammend the grammar to accept EOF.

**Comment by riastradh-probcomp** [comment]
bdb.execute('select')

**Comment by gregory-marton** [comment]
Fixed in 0.1.5 by giving context around syntax errors.

**Comment by riastradh-probcomp** [comment]
Date: Sat, 06 Feb 2016 03:08:16 -0800
   From: Gregory Marton <notifications@github.com>

   Fixed in 0.1.5 by giving context around syntax errors.

This is not fixed.

First, there's a new bug in the display of context:

>>> bdb.execute('select (1 +')
...
  File ".../bayeslite/parse.py", line 156, in syntax_error
    text, ' '.join([tok for (pos, tok) in self.context[:-1]])))
TypeError: sequence item 2: expected string, int found

The problem is that not all token values are strings.  If I work
around this by doing ' '.join([str(tok) ...]) (which is not clearly
the right thing but expedient for the moment), I get:

bayeslite.parse.BQLParseError: Syntax error near [;] after [select ( 1 +]

That is, bayeslite still insists that there is a syntax error at a
semicolon when there was no semicolon in the input I gave it.

**Comment by gregory-marton** [comment]
Fixed in e4a8ec2 and 6472fcc. Thanks for the heads-up on both!

<img width="1097" alt="screen shot 2016-02-07 at 10 21 48 pm" src="https://cloud.githubusercontent.com/assets/5065456/12877944/b18be07a-cde9-11e5-8284-5ee2e921d3fe.png">
